# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  base_url: https://fera-inc.github.io/fera/
  secret_key: "himanshu-is-not-fool-like-you--always-be-kind-12345"  # change this!
  limiter: true  # enable this when running the instance for a public usage on the internet
  image_proxy: true
redis:
  url: redis://redis:6379/0
